// ===============================================================
// Structured content for all inner pages.
// Route taxonomy: /services, /addonai, /industries, /case-studies, /blog
// ===============================================================

export type Feature = { icon: string; title: string; desc: string };
export type Stat = { value: string; label: string };

// -------------------- ADDON AI -------------------- //
export type AIService = {
  slug: string;
  title: string;
  eyebrow: string;
  subtitle: string;
  features: Feature[];
  process: string[];
  techStack: string[];
};

export const AI_SERVICES: AIService[] = [
  {
    slug: "ai-development",
    title: "AI Development",
    eyebrow: "Production-grade AI",
    subtitle: "End-to-end AI application development from data pipelines to production deployment.",
    features: [
      { icon: "Database", title: "Data pipeline design", desc: "Scalable ETL pipelines that ingest, transform, and prepare data from any source for model training and inference." },
      { icon: "Cpu", title: "Custom model training", desc: "Fine-tune models on your proprietary data using state-of-the-art architectures and hyperparameter optimization." },
      { icon: "Server", title: "MLOps & deployment", desc: "Production-grade deployment with CI/CD pipelines, A/B testing, model versioning, and automated retraining." },
      { icon: "Shield", title: "AI governance", desc: "Built-in bias detection, explainability layers, and compliance monitoring for responsible AI deployment." },
      { icon: "Chart", title: "Performance monitoring", desc: "Real-time dashboards tracking model drift, accuracy metrics, latency, and business KPI impact." },
      { icon: "Plug", title: "API-first architecture", desc: "RESTful and GraphQL APIs with auto-scaling, rate limiting, and comprehensive documentation." },
    ],
    process: ["Discovery & data audit", "Architecture design", "Model development", "Testing & validation", "Deployment & monitoring", "Continuous optimization"],
    techStack: ["Python", "TensorFlow", "PyTorch", "AWS SageMaker", "MLflow", "Kubernetes", "Docker", "Apache Spark"],
  },
  {
    slug: "ai-consulting",
    title: "AI Consulting",
    eyebrow: "Strategy before stack",
    subtitle: "Strategic AI roadmapping and technology advisory for maximum ROI.",
    features: [
      { icon: "Check", title: "AI readiness assessment", desc: "Comprehensive evaluation of your data maturity, infrastructure, team capabilities, and organisational readiness." },
      { icon: "Map", title: "Strategic roadmapping", desc: "Multi-phase implementation roadmaps aligned with business objectives, budgets, and competitive landscape." },
      { icon: "Calculator", title: "ROI modelling", desc: "Detailed financial models projecting costs, efficiency gains, revenue impact, and payback timelines." },
      { icon: "Search", title: "Use case identification", desc: "Systematic analysis of your operations to identify high-impact AI use cases ranked by feasibility and value." },
      { icon: "People", title: "Vendor selection", desc: "Unbiased technology and vendor evaluations covering platforms, models, tools, and cloud providers." },
      { icon: "Book", title: "Team enablement", desc: "Training programmes and workshops to upskill your teams on AI literacy, data practices, and tool adoption." },
    ],
    process: ["Stakeholder interviews", "Data & infrastructure audit", "Use case prioritisation", "Architecture blueprint", "ROI analysis", "Implementation roadmap"],
    techStack: ["AWS", "Azure", "GCP", "OpenAI", "Anthropic", "Hugging Face", "Databricks", "Snowflake"],
  },
  {
    slug: "generative-ai-development",
    title: "Generative AI Development",
    eyebrow: "Foundation models at work",
    subtitle: "Custom LLM applications and content generation powered by foundation models.",
    features: [
      { icon: "Language", title: "LLM fine-tuning", desc: "Fine-tune GPT, Claude, Llama, and Mistral models on your domain data for specialised, high-accuracy applications." },
      { icon: "File", title: "Content generation", desc: "Automated content pipelines producing marketing copy, reports, product descriptions, and documentation at scale." },
      { icon: "Image", title: "Multi-modal AI", desc: "Applications that understand and generate text, images, audio, and video using cutting-edge diffusion and transformer models." },
      { icon: "Terminal", title: "Prompt engineering", desc: "Optimised prompt architectures with chain-of-thought reasoning, few-shot learning, and automated prompt testing frameworks." },
      { icon: "Shield", title: "Safety & guardrails", desc: "Content filtering, output validation, and toxicity detection to ensure generated content meets compliance standards." },
      { icon: "Code", title: "Code generation", desc: "AI-powered code assistants and automated code review tools that accelerate development velocity." },
    ],
    process: ["Requirements analysis", "Model selection", "Prompt architecture", "Fine-tuning & testing", "Safety validation", "Production deployment"],
    techStack: ["OpenAI", "Claude", "Llama 3", "Stable Diffusion", "LangChain", "Pinecone", "Weights & Biases", "RLHF"],
  },
  {
    slug: "ai-chatbot-development",
    title: "AI Chatbot Development",
    eyebrow: "Conversational AI",
    subtitle: "Intelligent conversational interfaces that understand context and intent.",
    features: [
      { icon: "Cpu", title: "Natural language understanding", desc: "Advanced NLU engines that understand intent, extract entities, handle ambiguity, and maintain conversation context." },
      { icon: "Globe", title: "Multi-channel deployment", desc: "Deploy across web, mobile, WhatsApp, Slack, Teams, and voice assistants from a single conversational logic layer." },
      { icon: "Plug", title: "CRM & system integration", desc: "Deep integrations with Salesforce, HubSpot, Zendesk, and custom backends for personalised conversations." },
      { icon: "Language", title: "Multilingual support", desc: "Real-time translation and native support for 50+ languages with cultural context awareness." },
      { icon: "People", title: "Human hand-off", desc: "Intelligent escalation to live agents with full conversation context, sentiment analysis, and priority routing." },
      { icon: "Chart", title: "Analytics dashboard", desc: "Conversation analytics tracking resolution rates, satisfaction scores, common queries, and bot performance." },
    ],
    process: ["Conversation design", "NLU training", "Integration development", "User testing", "Deployment & launch", "Continuous learning"],
    techStack: ["Dialogflow", "Rasa", "LangChain", "OpenAI", "Node.js", "React", "WebSocket", "Redis"],
  },
  {
    slug: "ai-agents-development",
    title: "AI Agents Development",
    eyebrow: "Autonomous operators",
    subtitle: "Autonomous AI agents that reason, plan, and execute complex workflows.",
    features: [
      { icon: "Network", title: "Multi-agent orchestration", desc: "Design and deploy teams of specialised agents that collaborate, delegate tasks, and share context to solve complex workflows." },
      { icon: "Wrench", title: "Tool-use capabilities", desc: "Agents that autonomously interact with APIs, databases, file systems, browsers, and third-party services." },
      { icon: "Cpu", title: "Reasoning & planning", desc: "Advanced chain-of-thought and tree-of-thought reasoning for agents that break down complex problems into executable steps." },
      { icon: "Database", title: "Long-term memory", desc: "Persistent memory systems that let agents learn from past interactions, maintain context, and improve over time." },
      { icon: "Shield", title: "Enterprise guardrails", desc: "Configurable safety boundaries, approval workflows, audit trails, and rollback capabilities for controlled autonomy." },
      { icon: "Refresh", title: "Self-healing systems", desc: "Agents that detect failures, retry with alternative strategies, and escalate to humans when confidence is low." },
    ],
    process: ["Workflow analysis", "Agent architecture", "Tool integration", "Safety framework", "Evaluation & testing", "Monitored deployment"],
    techStack: ["LangGraph", "AutoGen", "CrewAI", "Claude", "OpenAI", "Python", "FastAPI", "PostgreSQL"],
  },
  {
    slug: "machine-learning-development",
    title: "Machine Learning Development",
    eyebrow: "Models in production",
    subtitle: "Predictive models and recommendation systems trained on your data.",
    features: [
      { icon: "Chart", title: "Predictive analytics", desc: "Forecast demand, revenue, churn, and market trends using advanced regression, time-series, and ensemble models." },
      { icon: "Star", title: "Recommendation engines", desc: "Personalised product, content, and service recommendations that increase engagement, conversion, and average order value." },
      { icon: "Alert", title: "Anomaly detection", desc: "Real-time detection of fraud, system failures, quality issues, and security threats using advanced methods." },
      { icon: "Tag", title: "Classification systems", desc: "Automated categorisation of documents, support tickets, images, and transactions with high accuracy and low latency." },
      { icon: "Network", title: "Feature engineering", desc: "Automated and expert-driven feature extraction, selection, and transformation to maximise model performance." },
      { icon: "Beaker", title: "A/B testing frameworks", desc: "Rigorous experimentation frameworks to validate model impact with statistical significance before full deployment." },
    ],
    process: ["Data exploration", "Feature engineering", "Model selection", "Training & tuning", "Validation & testing", "Production MLOps"],
    techStack: ["scikit-learn", "XGBoost", "LightGBM", "TensorFlow", "Apache Spark", "MLflow", "Airflow", "AWS SageMaker"],
  },
  {
    slug: "computer-vision",
    title: "Computer Vision",
    eyebrow: "Pixels to decisions",
    subtitle: "Image recognition, object detection, and visual analytics solutions.",
    features: [
      { icon: "Target", title: "Object detection & tracking", desc: "Real-time detection and tracking of objects across video streams for surveillance, retail analytics, and autonomous systems." },
      { icon: "Search", title: "Visual quality inspection", desc: "Automated defect detection for manufacturing, achieving sub-millimeter accuracy and replacing manual inspection workflows." },
      { icon: "File", title: "OCR & document processing", desc: "Extract structured data from invoices, receipts, forms, and handwritten documents with intelligent field mapping." },
      { icon: "Smile", title: "Facial recognition", desc: "Secure identity verification, emotion analysis, and demographic analytics for access control and customer experience." },
      { icon: "Image", title: "Image segmentation", desc: "Pixel-level segmentation for medical imaging, satellite analysis, autonomous driving, and augmented reality." },
      { icon: "Video", title: "Video analytics", desc: "Automated event detection, activity recognition, and behaviour analysis across multi-camera video surveillance systems." },
    ],
    process: ["Data collection & labelling", "Model architecture", "Training & augmentation", "Edge optimisation", "Integration & testing", "Deployment & monitoring"],
    techStack: ["OpenCV", "YOLO", "TensorRT", "ONNX", "PyTorch", "NVIDIA Triton", "AWS Rekognition", "Edge TPU"],
  },
  {
    slug: "rpa-development",
    title: "RPA Development",
    eyebrow: "Automating the boring",
    subtitle: "Robotic process automation that eliminates repetitive manual tasks.",
    features: [
      { icon: "Bot", title: "Process automation bots", desc: "Software robots that handle data entry, file transfers, form filling, and repetitive tasks across any desktop or web application." },
      { icon: "File", title: "Intelligent document processing", desc: "Combine OCR, NLP, and machine learning to extract, classify, and route information from unstructured documents." },
      { icon: "Refresh", title: "Workflow orchestration", desc: "End-to-end orchestration of multi-system workflows with scheduling, error handling, and SLA monitoring." },
      { icon: "Gauge", title: "Process mining", desc: "Discover and analyse existing business processes from system logs to identify automation candidates and bottlenecks." },
      { icon: "People", title: "Attended automation", desc: "Digital assistants that work alongside employees, automating routine steps while humans handle exceptions and decisions." },
      { icon: "Chart", title: "ROI analytics", desc: "Dashboards tracking bot performance, hours saved, error reduction, and cost savings per automated process." },
    ],
    process: ["Process discovery", "Feasibility assessment", "Bot development", "Testing & UAT", "Deployment & training", "Monitoring & optimisation"],
    techStack: ["UiPath", "Automation Anywhere", "Power Automate", "Python", "Selenium", "API Integration", "OCR Engines", "Azure"],
  },
  {
    slug: "rag-development",
    title: "RAG Development",
    eyebrow: "Grounded generation",
    subtitle: "Retrieval-Augmented Generation for accurate, source-cited AI responses.",
    features: [
      { icon: "Database", title: "Vector database design", desc: "Optimised vector store architecture using Pinecone, Weaviate, or Qdrant for lightning-fast semantic search at scale." },
      { icon: "Target", title: "Knowledge base pipelines", desc: "Automated ingestion pipelines that chunk, embed, and index documents from PDFs, databases, wikis, and APIs." },
      { icon: "Quote", title: "Citation & sourcing", desc: "Every AI response includes verifiable source citations with page numbers, links, and confidence scores." },
      { icon: "Search", title: "Hybrid search", desc: "Combine semantic vector search with keyword-based BM25 retrieval and metadata filtering for maximum relevance." },
      { icon: "Lock", title: "Access control", desc: "Document-level permissions ensuring users only access information they are authorised to see." },
      { icon: "Refresh", title: "Real-time sync", desc: "Incremental indexing that keeps your knowledge base current as documents are added, modified, or archived." },
    ],
    process: ["Knowledge audit", "Chunking strategy", "Embedding pipeline", "Retrieval tuning", "LLM integration", "Evaluation & launch"],
    techStack: ["Pinecone", "Weaviate", "LangChain", "LlamaIndex", "OpenAI Embeddings", "pgvector", "FastAPI", "Redis"],
  },
];

// -------------------- SERVICES -------------------- //
export type Service = {
  slug: string;
  title: string;
  eyebrow: string;
  subtitle: string;
  features: Feature[];
  process: string[];
  techStack: string[];
};

export const SERVICES_DATA: Service[] = [
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    eyebrow: "iOS · Android · Cross-platform",
    subtitle: "Native and cross-platform mobile apps for iOS and Android.",
    features: [
      { icon: "Smartphone", title: "iOS development", desc: "Native Swift and SwiftUI applications optimised for performance, accessibility, and the latest Apple ecosystem features." },
      { icon: "Smartphone", title: "Android development", desc: "Kotlin-first Android apps with Material Design 3, Jetpack Compose, and seamless Google Play Store deployment." },
      { icon: "Layers", title: "Cross-platform", desc: "Flutter and React Native solutions delivering native-quality experiences on both platforms from a single codebase." },
      { icon: "Pen", title: "UI/UX design", desc: "User-centred design with wireframes, prototypes, usability testing, and pixel-perfect implementation." },
      { icon: "Bolt", title: "App performance", desc: "Optimised rendering, lazy loading, efficient state management, and minimal battery consumption for smooth experiences." },
      { icon: "Cloud", title: "Backend & APIs", desc: "Scalable cloud backends with real-time sync, push notifications, authentication, and offline-first architectures." },
    ],
    process: ["Product strategy", "UI/UX design", "Development sprint", "QA & testing", "App store launch", "Post-launch support"],
    techStack: ["Swift", "Kotlin", "Flutter", "React Native", "Firebase", "Node.js", "GraphQL", "AWS Amplify"],
  },
  {
    slug: "web-development",
    title: "Web Development",
    eyebrow: "Full-stack web apps",
    subtitle: "High-performance web applications with modern frameworks.",
    features: [
      { icon: "Code", title: "Frontend development", desc: "Modern SPAs and SSR applications built with React, Next.js, Vue, and Angular with optimal Core Web Vitals." },
      { icon: "Server", title: "Backend systems", desc: "Scalable APIs and microservices using Node.js, Python, Go, or Java with clean architecture and testing." },
      { icon: "Cart", title: "eCommerce platforms", desc: "Custom storefronts, headless commerce, and marketplace solutions with payment integration and inventory management." },
      { icon: "Palette", title: "UI/UX engineering", desc: "Responsive design systems, animation libraries, and accessible interfaces that meet WCAG 2.1 AA standards." },
      { icon: "Gauge", title: "Performance optimisation", desc: "Sub-second load times through code splitting, CDN optimisation, image compression, and edge computing." },
      { icon: "Puzzle", title: "CMS & integrations", desc: "Headless CMS solutions with Contentful, Strapi, or Sanity, plus integrations with CRMs, ERPs, and analytics." },
    ],
    process: ["Requirements analysis", "Architecture & design", "Agile development", "QA & performance", "Deployment & CI/CD", "Maintenance & support"],
    techStack: ["React", "Next.js", "Vue.js", "Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker"],
  },
  {
    slug: "iot-development",
    title: "IoT Development",
    eyebrow: "Connected devices",
    subtitle: "Connected device ecosystems and IoT platform solutions.",
    features: [
      { icon: "Wifi", title: "Device connectivity", desc: "Multi-protocol support for MQTT, CoAP, BLE, Zigbee, and LoRaWAN connecting thousands of devices reliably." },
      { icon: "Cloud", title: "IoT cloud platforms", desc: "Custom platforms on AWS IoT, Azure IoT Hub, or Google Cloud IoT for device management, data ingestion, and analytics." },
      { icon: "Cpu", title: "Edge computing", desc: "On-device processing and AI inference at the edge for low-latency decision-making without cloud dependency." },
      { icon: "Chart", title: "Real-time analytics", desc: "Stream processing pipelines that transform raw sensor data into actionable dashboards and automated alerts." },
      { icon: "Shield", title: "IoT security", desc: "End-to-end encryption, secure boot, OTA updates, and device authentication to protect your connected ecosystem." },
      { icon: "Network", title: "Digital twins", desc: "Virtual replicas of physical assets for simulation, monitoring, predictive maintenance, and scenario planning." },
    ],
    process: ["Hardware assessment", "Architecture design", "Firmware development", "Cloud integration", "Security hardening", "Deployment & monitoring"],
    techStack: ["AWS IoT Core", "MQTT", "Raspberry Pi", "Arduino", "TensorFlow Lite", "InfluxDB", "Grafana", "Kubernetes"],
  },
  {
    slug: "blockchain-solutions",
    title: "Blockchain Solutions",
    eyebrow: "Smart contracts · Web3",
    subtitle: "Smart contracts, DeFi platforms, and decentralised applications.",
    features: [
      { icon: "File", title: "Smart contracts", desc: "Secure, audited smart contracts on Ethereum, Solana, and Polygon for DeFi, NFTs, governance, and supply chain." },
      { icon: "Coin", title: "DeFi platforms", desc: "Decentralised exchanges, lending protocols, yield aggregators, and liquidity pools with robust security auditing." },
      { icon: "Image", title: "NFT marketplaces", desc: "Custom NFT minting, marketplace, and auction platforms with royalty management and multi-chain support." },
      { icon: "Network", title: "Supply chain tracking", desc: "Immutable ledger systems for end-to-end supply chain provenance, authentication, and compliance verification." },
      { icon: "Wallet", title: "Wallet integration", desc: "Web3 wallet connections with MetaMask, WalletConnect, and custodial solutions for seamless user onboarding." },
      { icon: "Shield", title: "Security auditing", desc: "Comprehensive smart contract audits covering reentrancy, overflow, access control, and economic exploit vectors." },
    ],
    process: ["Use case analysis", "Token economics", "Smart contract development", "Security audit", "Testnet deployment", "Mainnet launch"],
    techStack: ["Solidity", "Rust", "Ethereum", "Solana", "Polygon", "Hardhat", "Web3.js", "IPFS"],
  },
  {
    slug: "product-consulting",
    title: "Product Consulting",
    eyebrow: "Product strategy",
    subtitle: "Product strategy, UX research, and go-to-market planning.",
    features: [
      { icon: "Target", title: "Product strategy", desc: "Market research, competitive analysis, and product-market fit validation to define a winning product vision." },
      { icon: "People", title: "UX research", desc: "User interviews, surveys, usability testing, and persona development to build products users actually need." },
      { icon: "Pen", title: "Design sprints", desc: "Rapid prototyping and validation cycles that compress months of discovery into focused one-week sprints." },
      { icon: "Map", title: "Product roadmapping", desc: "Prioritised feature roadmaps balancing user needs, technical feasibility, and business impact with clear milestones." },
      { icon: "Rocket", title: "Go-to-market strategy", desc: "Launch planning covering positioning, pricing, distribution channels, and growth metrics for successful market entry." },
      { icon: "Chart", title: "Analytics & growth", desc: "Instrumentation, funnel analysis, cohort tracking, and data-driven experimentation for continuous product improvement." },
    ],
    process: ["Discovery workshop", "User research", "Ideation & prioritisation", "Prototype & test", "Roadmap delivery", "Launch support"],
    techStack: ["Figma", "Miro", "Amplitude", "Mixpanel", "Jira", "Notion", "Hotjar", "Segment"],
  },
  {
    slug: "outsourcing",
    title: "Business Collaboration & Outsourcing",
    eyebrow: "Dedicated teams",
    subtitle: "Dedicated teams and staff augmentation for your projects.",
    features: [
      { icon: "People", title: "Dedicated teams", desc: "Full-time engineers, designers, and PMs integrated into your workflow with direct communication and shared tools." },
      { icon: "People", title: "Staff augmentation", desc: "Scale your team rapidly with pre-vetted specialists who can contribute from day one, no ramp-up delays." },
      { icon: "Building", title: "Offshore development centre", desc: "Your own branded development centre with dedicated workspace, infrastructure, and management support." },
      { icon: "Clock", title: "Flexible engagement", desc: "Choose from fixed-price, time-and-material, or retainer models based on project scope and timeline requirements." },
      { icon: "Chat", title: "Transparent communication", desc: "Daily standups, weekly demos, Slack channels, and shared project management tools for full visibility." },
      { icon: "Check", title: "Quality assurance", desc: "Dedicated QA engineers, code reviews, automated testing, and compliance with your quality standards and processes." },
    ],
    process: ["Requirement analysis", "Team assembly", "Onboarding & integration", "Sprint execution", "Review & iterate", "Scale & optimise"],
    techStack: ["Jira", "Confluence", "Slack", "GitHub", "CI/CD", "Agile/Scrum", "Code review", "Documentation"],
  },
  {
    slug: "cloud-services",
    title: "Cloud Services",
    eyebrow: "AWS · Azure · GCP",
    subtitle: "Cloud architecture, migration, and DevOps on AWS, Azure, and GCP.",
    features: [
      { icon: "Building", title: "Cloud architecture", desc: "Design scalable, fault-tolerant architectures on AWS, Azure, or GCP following Well-Architected Framework best practices." },
      { icon: "Refresh", title: "Cloud migration", desc: "Lift-and-shift, re-platform, or re-architect strategies with zero-downtime migration and comprehensive testing." },
      { icon: "Infinity", title: "DevOps & CI/CD", desc: "Infrastructure as Code with Terraform, automated pipelines with GitHub Actions, and GitOps workflows for reliable deployments." },
      { icon: "Cube", title: "Containerisation", desc: "Docker and Kubernetes orchestration with service mesh, auto-scaling, and multi-region deployments." },
      { icon: "Shield", title: "Security & compliance", desc: "IAM policies, encryption, VPC design, WAF configuration, and compliance frameworks (SOC 2, HIPAA, GDPR)." },
      { icon: "Money", title: "Cost optimisation", desc: "Reserved instances, spot fleets, right-sizing, and FinOps practices to reduce cloud spend by 30–50%." },
    ],
    process: ["Cloud assessment", "Architecture design", "Migration planning", "Implementation", "Security hardening", "Optimisation & FinOps"],
    techStack: ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Docker", "GitHub Actions", "Datadog"],
  },
  {
    slug: "digital-transformation",
    title: "Digital Transformation",
    eyebrow: "Modernise the stack",
    subtitle: "Modernise legacy systems and adopt digital-first strategies.",
    features: [
      { icon: "Building", title: "Legacy modernisation", desc: "Migrate monolithic systems to cloud-native microservices with zero downtime and incremental refactoring strategies." },
      { icon: "Bot", title: "Process automation", desc: "Digitise manual workflows with intelligent automation, reducing errors and cycle times across departments." },
      { icon: "Database", title: "Data platform", desc: "Unified data lakes, real-time analytics, and self-service BI tools that turn raw data into strategic decisions." },
      { icon: "Smartphone", title: "Digital experience", desc: "Customer-facing portals, mobile apps, and self-service platforms that modernise engagement touchpoints." },
      { icon: "People", title: "Change management", desc: "Training, communication, and adoption strategies to ensure your team embraces new digital tools and processes." },
      { icon: "Gauge", title: "Performance benchmarking", desc: "KPI dashboards and maturity assessments that measure transformation progress against industry benchmarks." },
    ],
    process: ["Digital maturity assessment", "Vision & strategy", "Technology selection", "Phased implementation", "Change management", "Continuous improvement"],
    techStack: ["Microservices", "Event-driven architecture", "API Gateway", "Kafka", "Cloud Native", "Low-Code", "RPA", "BI Tools"],
  },
  {
    slug: "quality-assurance",
    title: "Quality Assurance",
    eyebrow: "Test with rigour",
    subtitle: "Automated testing, security audits, and performance optimisation.",
    features: [
      { icon: "Beaker", title: "Automated testing", desc: "End-to-end test automation using Cypress, Playwright, and Selenium covering UI, API, and integration scenarios." },
      { icon: "Gauge", title: "Performance testing", desc: "Load, stress, and scalability testing with JMeter and k6 to identify bottlenecks before they impact users." },
      { icon: "Shield", title: "Security testing", desc: "Penetration testing, OWASP vulnerability scanning, and security code review to harden your applications." },
      { icon: "Smartphone", title: "Mobile QA", desc: "Cross-device testing on real devices and emulators covering iOS, Android, various screen sizes, and OS versions." },
      { icon: "Check", title: "Accessibility testing", desc: "WCAG 2.1 compliance testing with screen reader validation and keyboard navigation verification." },
      { icon: "Network", title: "CI/CD integration", desc: "Test suites integrated into your CI/CD pipeline for automated quality gates on every code change." },
    ],
    process: ["Test strategy", "Test plan & cases", "Environment setup", "Test execution", "Defect management", "Reporting & sign-off"],
    techStack: ["Cypress", "Playwright", "Selenium", "JMeter", "k6", "Appium", "Postman", "SonarQube"],
  },
];

// -------------------- INDUSTRIES -------------------- //
export type Industry = {
  slug: string;
  title: string;
  eyebrow: string;
  subtitle: string;
  challenges: string[];
  solutions: string[];
  stats: Stat[];
};

export const INDUSTRIES: Industry[] = [
  {
    slug: "healthcare",
    title: "Healthcare",
    eyebrow: "Healthcare technology",
    subtitle: "Transforming patient care with intelligent health technology solutions.",
    challenges: ["Patient data fragmentation across systems", "Long wait times and scheduling inefficiencies", "Regulatory compliance (HIPAA, HITECH)", "Manual diagnostic processes"],
    solutions: ["EHR integration and unified patient portals", "AI-powered triage and appointment optimisation", "Automated compliance monitoring and reporting", "Computer vision for medical imaging analysis"],
    stats: [{ value: "60%", label: "Reduction in wait times" }, { value: "99.7%", label: "HIPAA compliance rate" }, { value: "45%", label: "Faster diagnostics" }],
  },
  {
    slug: "fintech",
    title: "FinTech",
    eyebrow: "Financial technology",
    subtitle: "Secure, scalable financial technology for the modern economy.",
    challenges: ["Increasing fraud sophistication", "Complex regulatory requirements (PCI DSS, SOX)", "Legacy core banking systems", "Customer demand for real-time services"],
    solutions: ["ML-powered real-time fraud detection engines", "Automated regulatory reporting and compliance", "API-first banking platform modernisation", "Instant payments and digital wallet solutions"],
    stats: [{ value: "99.7%", label: "Fraud detection accuracy" }, { value: "$2M+", label: "Annual savings per client" }, { value: "2M+", label: "Daily transactions processed" }],
  },
  {
    slug: "ecommerce",
    title: "eCommerce",
    eyebrow: "Omnichannel commerce",
    subtitle: "Omnichannel commerce platforms that drive revenue growth.",
    challenges: ["Cart abandonment and low conversion rates", "Inventory management across channels", "Personalisation at scale", "Peak traffic scalability"],
    solutions: ["AI-driven recommendation engines and dynamic pricing", "Unified inventory and order management systems", "Personalised shopping experiences with ML", "Auto-scaling cloud infrastructure for flash sales"],
    stats: [{ value: "35%", label: "Increase in conversion" }, { value: "$50M+", label: "GMV managed" }, { value: "100K+", label: "Concurrent users" }],
  },
  {
    slug: "logistics",
    title: "Logistics",
    eyebrow: "Supply chain & fleet",
    subtitle: "Supply chain optimisation through intelligent automation.",
    challenges: ["Route optimisation complexity", "Real-time fleet visibility", "Last-mile delivery costs", "Supply chain disruption forecasting"],
    solutions: ["AI-powered route optimisation algorithms", "IoT fleet tracking with real-time dashboards", "Automated dispatch and delivery scheduling", "Predictive supply chain analytics"],
    stats: [{ value: "25%", label: "Fuel cost reduction" }, { value: "10K+", label: "Vehicles tracked" }, { value: "40%", label: "Faster deliveries" }],
  },
  {
    slug: "education",
    title: "Education",
    eyebrow: "EdTech at scale",
    subtitle: "EdTech solutions that personalise learning at scale.",
    challenges: ["One-size-fits-all learning approaches", "Student engagement and retention", "Administrative overhead", "Remote learning quality"],
    solutions: ["Adaptive learning paths powered by AI", "Gamification and interactive content platforms", "Automated grading and administrative workflows", "High-quality video conferencing and collaboration tools"],
    stats: [{ value: "500K+", label: "Students served" }, { value: "40%", label: "Better retention" }, { value: "60%", label: "Admin time saved" }],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    eyebrow: "PropTech",
    subtitle: "PropTech platforms for modern property management and sales.",
    challenges: ["Fragmented property listing data", "Manual valuation processes", "Tenant communication overhead", "Property maintenance scheduling"],
    solutions: ["Unified MLS integration and search platforms", "AI-powered property valuation models", "Tenant portals with automated communication", "IoT-enabled predictive maintenance systems"],
    stats: [{ value: "30%", label: "Faster closings" }, { value: "95%", label: "Valuation accuracy" }, { value: "50%", label: "Fewer maintenance calls" }],
  },
  {
    slug: "on-demand",
    title: "On-Demand",
    eyebrow: "Marketplace & gig",
    subtitle: "Marketplace and on-demand service platforms that scale.",
    challenges: ["Matching supply with real-time demand", "Driver/provider retention", "Dynamic pricing optimisation", "Multi-sided marketplace complexity"],
    solutions: ["AI matching algorithms with demand prediction", "Incentive optimisation and loyalty programmes", "Surge pricing with fairness algorithms", "Scalable marketplace architecture"],
    stats: [{ value: "3×", label: "Faster matching" }, { value: "40%", label: "Better retention" }, { value: "99.9%", label: "Platform uptime" }],
  },
  {
    slug: "manufacturing",
    title: "Manufacturing",
    eyebrow: "Industry 4.0",
    subtitle: "Smart manufacturing solutions with IoT and AI integration.",
    challenges: ["Unplanned equipment downtime", "Quality control inconsistencies", "Supply chain visibility gaps", "Energy consumption optimisation"],
    solutions: ["IoT sensors with predictive maintenance AI", "Computer vision quality inspection systems", "Real-time supply chain tracking dashboards", "AI-driven energy management and optimisation"],
    stats: [{ value: "45%", label: "Less downtime" }, { value: "99.2%", label: "Defect detection" }, { value: "30%", label: "Energy savings" }],
  },
  {
    slug: "automotive",
    title: "Automotive",
    eyebrow: "Connected vehicles",
    subtitle: "Connected vehicle solutions and automotive tech platforms.",
    challenges: ["Connected vehicle data management", "Dealership digital experience", "Aftermarket service optimisation", "EV charging infrastructure"],
    solutions: ["Vehicle telematics platforms with OTA updates", "Digital showroom and configurator experiences", "Predictive service scheduling and parts management", "EV charging network management systems"],
    stats: [{ value: "50%", label: "Service revenue increase" }, { value: "35%", label: "Better customer satisfaction" }, { value: "10K+", label: "Connected vehicles" }],
  },
  {
    slug: "travel",
    title: "Travel",
    eyebrow: "Travel technology",
    subtitle: "Travel tech that enhances booking and guest experiences.",
    challenges: ["Price comparison and booking complexity", "Personalisation across touchpoints", "Dynamic inventory management", "Post-booking engagement"],
    solutions: ["AI-powered fare prediction and booking engines", "Hyper-personalised travel recommendations", "Real-time inventory sync across OTAs and direct", "Automated itinerary management and concierge bots"],
    stats: [{ value: "28%", label: "Booking conversion increase" }, { value: "45%", label: "Higher repeat bookings" }, { value: "3×", label: "Engagement rate" }],
  },
  {
    slug: "restaurant",
    title: "Restaurant",
    eyebrow: "Food service tech",
    subtitle: "Restaurant management and ordering platform solutions.",
    challenges: ["Order management across platforms", "Kitchen efficiency and waste reduction", "Customer loyalty and retention", "Staff scheduling complexity"],
    solutions: ["Unified POS with multi-platform order aggregation", "AI-powered inventory and waste prediction", "Digital loyalty programmes with personalised offers", "Automated scheduling based on demand forecasting"],
    stats: [{ value: "35%", label: "Reduction in food waste" }, { value: "25%", label: "Revenue increase" }, { value: "50%", label: "Faster order processing" }],
  },
  {
    slug: "retail",
    title: "Retail",
    eyebrow: "Unified commerce",
    subtitle: "Retail technology for unified commerce and customer engagement.",
    challenges: ["Omnichannel inventory complexity", "In-store and online experience gap", "Customer data unification", "Dynamic pricing and promotions"],
    solutions: ["Unified commerce platform with real-time inventory", "AR try-on and personalised in-store experiences", "Customer data platform with 360-degree profiles", "AI-driven pricing and promotional optimisation"],
    stats: [{ value: "40%", label: "Higher AOV" }, { value: "30%", label: "Inventory accuracy improvement" }, { value: "55%", label: "Customer retention increase" }],
  },
];

// -------------------- CASE STUDIES -------------------- //
export type CaseStudyDetail = {
  slug: string;
  title: string;
  client: string;
  industry: string;
  categories: string[];
  subtitle: string;
  overview: string;
  challenge: string;
  solution: string;
  keyFeatures: Feature[];
  results: Stat[];
  techStack: string[];
};

export const CASE_STUDIES_DATA: CaseStudyDetail[] = [
  {
    slug: "camera-telematics",
    title: "Vehicle Tracking & Telematics with Real-Time Video",
    client: "A leading EU fleet solutions provider",
    industry: "IoT & Telematics",
    categories: ["IoT & Telematics"],
    subtitle: "Managing 4,000+ vehicles with 150M+ GPS data points daily for a leading EU fleet solutions provider since 2016.",
    overview: "An end-to-end telematics platform serving fleet owners and sensitive businesses like cash-in-transit and petroleum carriers across Europe. Real-time video footage is used as evidence for faster insurance claims while driver behaviour is scored against customisable goals.",
    challenge: "The client needed an advanced FNOL (First Notice of Loss) video-based telematics and tracking solution for fleet owners and sensitive businesses across Europe. The system had to handle real-time video streaming from thousands of in-vehicle cameras, process 150M+ daily GPS data points, integrate OBD-II via Bluetooth, and provide configurable driver behaviour scoring — all while maintaining sub-second response times for 4,000+ vehicles.",
    solution: "We built a comprehensive end-to-end telematics platform from the ground up — device-to-server code using socket programming, role-based dashboards for super admin, vendor admin and staff, native Android and iOS apps, real-time tracking on OpenStreetMap, driver leaderboards with configurable scoring, and a full REST API suite so vendors can embed the system in their own platforms.",
    keyFeatures: [
      { icon: "Wifi", title: "Real-time configuration", desc: "Tune speed, braking, cornering, acceleration and driver-score thresholds from the UI — adopted by the device on its next server connection." },
      { icon: "Pin", title: "Live vehicle tracking", desc: "Real-time monitoring of 4,000+ devices with custom reporting and 150M+ GPS data points processed daily." },
      { icon: "Video", title: "FNOL video evidence", desc: "Real-time footage from in-vehicle cameras used as evidence for faster insurance claim processing and incident analysis." },
      { icon: "Car", title: "OBD-II ECU integration", desc: "Vehicle diagnostics via Bluetooth OBD-II providing engine health, fuel consumption, and performance metrics." },
      { icon: "Trophy", title: "Driver leaderboard & scoring", desc: "Behaviour scoring with custom goals and scorecards to improve driving habits and reduce accidents." },
      { icon: "Smartphone", title: "Native mobile apps", desc: "Vendor-branded Android app for phones and tablets and iOS app for iPhone and iPad with full dashboard parity." },
      { icon: "Shield", title: "Multi-tenant CMS", desc: "Separate super admin and vendor admin backends with role-based access control for staff and employees." },
      { icon: "Plug", title: "REST API suite", desc: "Complete REST APIs so vendors can embed the tracking system into any other platform or custom UI." },
    ],
    results: [{ value: "4,000+", label: "Vehicles tracked" }, { value: "150M+", label: "Daily GPS points" }, { value: "10+", label: "Years partnership" }, { value: "24/7", label: "Real-time monitoring" }],
    techStack: ["Java", "Hibernate", "Socket programming", "Jersey", "Swift", "MySQL", "Azure", "OpenStreetMap", "REST APIs"],
  },
  {
    slug: "obd2-telematics",
    title: "OBD-II Telematics & Industrial IoT Platform",
    client: "A global industrial IoT company",
    industry: "IoT & Industrial",
    categories: ["IoT & Telematics", "Enterprise & CRM"],
    subtitle: "Unified command centre with 200+ sensor types, RTLS, and AI-powered asset intelligence.",
    overview: "A unified industrial IoT command centre supporting 200+ sensor types, real-time location tracking, an AI assistant, and 8 native modules. Deployable across cloud, on-premise, air-gapped, and edge environments for manufacturing, defence, energy, and logistics.",
    challenge: "A growing industrial IoT company needed a unified command centre to manage thousands of assets across plants, warehouses, and field operations. Their existing systems were fragmented — separate tools for asset tracking, maintenance, sensor monitoring, and space management — leading to blind spots, delayed response times, and inefficiencies across 200+ sensor types.",
    solution: "We built an all-in-one OBD-II telematics and industrial IoT platform featuring native modules for asset management, an IoT hub with 200+ sensor integrations, CMMS for preventive maintenance, real-time location tracking, interactive dashboards, workflow automation, space management, ticketing, and an AI assistant for operational intelligence. Supports cloud, on-premise, air-gapped, and edge deployment.",
    keyFeatures: [
      { icon: "Cube", title: "Asset management", desc: "Complete lifecycle tracking from procurement to retirement with real-time status, location, and maintenance history." },
      { icon: "Wifi", title: "IoT hub (200+ sensors)", desc: "Universal sensor integration supporting temperature, vibration, pressure, humidity, and custom industrial sensors." },
      { icon: "Wrench", title: "CMMS module", desc: "Maintenance management with preventive scheduling, work orders, and spare parts inventory." },
      { icon: "Pin", title: "Real-time location (RTLS)", desc: "Indoor and outdoor asset tracking with BLE beacons, UWB, and GPS for precise positioning." },
      { icon: "Chart", title: "Interactive dashboards", desc: "Customisable dashboards with drag-and-drop widgets, role-based views, and real-time data visualisation." },
      { icon: "Bot", title: "AI assistant", desc: "Natural-language query interface for operational intelligence — ask about assets, sensors, and trends." },
      { icon: "Bot", title: "Workflow automation", desc: "No-code automation builder for alerts, escalations, and conditional actions based on sensor data." },
      { icon: "Tag", title: "Ticketing", desc: "Integrated ticketing for issue reporting, assignment, and resolution tracking with SLA monitoring." },
    ],
    results: [{ value: "200+", label: "Sensor types supported" }, { value: "50K+", label: "Assets managed" }, { value: "35%", label: "Downtime reduction" }, { value: "8", label: "Native modules" }],
    techStack: ["Java", "Python", "MQTT", "AWS IoT Core", "React", "PostgreSQL", "TensorFlow", "Docker", "Kubernetes"],
  },
  {
    slug: "multi-iot-tracking",
    title: "Multi-IoT Device Tracking Platform",
    client: "A logistics & cold-chain provider",
    industry: "IoT & Logistics",
    categories: ["IoT & Telematics"],
    subtitle: "Real-time monitoring across temperature, humidity, geolocation and cold chain with ML optimisation.",
    overview: "A multi-IoT device tracking platform that unifies temperature sensors, humidity monitors, GPS trackers, door sensors, and accelerometers into a single real-time dashboard, with ML-powered spoilage prevention and regulatory reporting.",
    challenge: "A logistics company managing temperature-sensitive pharmaceutical and food shipments across multiple geographies lacked unified visibility into their IoT device fleet. Disparate sensor networks with no centralised platform meant they could not correlate data, trigger real-time alerts, or prevent spoilage events costing millions annually.",
    solution: "We developed a multi-IoT platform unifying data from temperature, humidity, GPS, door, and accelerometer sensors into a single real-time dashboard. It includes cold-chain compliance monitoring, geofencing with route adherence, ML spoilage prediction, and customisable regulatory reporting for food and pharma.",
    keyFeatures: [
      { icon: "Gauge", title: "Temperature monitoring", desc: "Continuous tracking with configurable thresholds and automated cold-chain alerts." },
      { icon: "Cloud", title: "Humidity & environment", desc: "Environmental monitoring for humidity, light exposure, and atmospheric pressure across routes." },
      { icon: "Pin", title: "GPS & geofencing", desc: "Real-time location tracking with geofence zones, route adherence, and deviation alerts." },
      { icon: "Lock", title: "Door & seal detection", desc: "Tamper detection with door-open sensors, seal-break alerts, and chain-of-custody audit trails." },
      { icon: "Cpu", title: "ML spoilage prediction", desc: "Machine-learning models predicting spoilage risk based on historical patterns and real-time conditions." },
      { icon: "Chart", title: "Compliance reporting", desc: "Automated regulatory reports for FDA, EU GDP, and HACCP with exportable audit trails." },
      { icon: "Alert", title: "Smart alerting", desc: "Multi-channel alerts via SMS, push, and email with escalation workflows and acknowledgement." },
      { icon: "Plug", title: "Sensor integration", desc: "Universal sensor hub supporting BLE, LoRaWAN, NB-IoT, and cellular across 50+ manufacturers." },
    ],
    results: [{ value: "10K+", label: "IoT devices tracked" }, { value: "98.5%", label: "Cold chain compliance" }, { value: "60%", label: "Spoilage reduction" }, { value: "24/7", label: "Real-time monitoring" }],
    techStack: ["Python", "IoT sensors", "AWS IoT Core", "React", "TensorFlow", "MongoDB", "Grafana", "MQTT"],
  },
  {
    slug: "multitenant-ecommerce",
    title: "Multi-tenant eCommerce with Multilingual",
    client: "A regional retail conglomerate",
    industry: "eCommerce",
    categories: ["eCommerce & Retail"],
    subtitle: "Scalable multi-tenant architecture supporting 8+ languages and 50K+ SKUs per tenant.",
    overview: "A multi-tenant eCommerce platform powering 12 independently-branded storefronts from a shared microservices backend, with 8+ languages including RTL scripts and centralised inventory.",
    challenge: "A retail conglomerate operating multiple brands across different countries needed a single platform powering independent storefronts for each brand while sharing a common backend. Separate Shopify stores were creating inventory sync nightmares and costing over $200K annually in redundant subscriptions.",
    solution: "We architected a multi-tenant platform with complete tenant isolation at the database level, a shared microservices backend, and independently deployable storefronts. Features include a centralised PIM, tenant-specific pricing and promotions, multilingual content with i18next for 8+ languages including Arabic and Hebrew RTL, unified inventory, and per-tenant payment gateways.",
    keyFeatures: [
      { icon: "Building", title: "Multi-tenant architecture", desc: "Complete tenant isolation with shared infrastructure — each brand gets independent storefront, admin, and data." },
      { icon: "Language", title: "Multilingual (8+ languages)", desc: "Full i18next integration supporting LTR and RTL scripts including Arabic, Hebrew, and CJK." },
      { icon: "Tag", title: "Tenant-specific pricing", desc: "Independent pricing rules, currency, tax configurations, and promotional campaigns per tenant." },
      { icon: "Cube", title: "Centralised PIM", desc: "Unified product information management with per-tenant catalogue overrides and automated sync." },
      { icon: "Wallet", title: "Payment gateway config", desc: "Per-tenant payment gateway selection with Stripe, PayPal, and local payment methods." },
      { icon: "Building", title: "Unified inventory", desc: "Real-time inventory sync across all tenants with automated stock allocation and alerts." },
      { icon: "Palette", title: "White-label theming", desc: "Drag-and-drop theme builder with custom branding, fonts, colours, and layout per tenant." },
      { icon: "Chart", title: "Cross-tenant analytics", desc: "Consolidated reporting across all brands with drill-down per tenant, region, and product." },
    ],
    results: [{ value: "12", label: "Tenant brands live" }, { value: "8+", label: "Languages supported" }, { value: "50K+", label: "SKUs per tenant" }, { value: "40%", label: "Operating cost reduction" }],
    techStack: ["React", "Node.js", "PostgreSQL", "Redis", "Stripe", "i18next", "Docker", "AWS", "GraphQL", "Elasticsearch"],
  },
  {
    slug: "automotive-crm",
    title: "Automotive Services, Scheduling & Parts CRM",
    client: "A national auto service chain",
    industry: "Automotive",
    categories: ["Automotive", "Enterprise & CRM"],
    subtitle: "End-to-end CRM for 25+ service centres with scheduling, parts ordering, and customer management.",
    overview: "An end-to-end automotive CRM connecting 25+ service centres with intelligent scheduling, automated parts ordering, and unified customer profiles.",
    challenge: "A national automotive service chain with 25+ locations was running on paper-based scheduling and manual parts ordering via phone and fax, with disconnected customer records across locations. Booking calls averaged 12 minutes, parts ordering had a 15% error rate, and management had zero visibility into customer history across branches.",
    solution: "We built an end-to-end CRM with intelligent appointment scheduling that factors technician specialisation, bay availability, and estimated service duration. The parts module integrates with distributor APIs for real-time pricing, auto-generates purchase orders, and tracks ETAs. A unified customer profile aggregates service history, vehicle details, upcoming maintenance, and communication preferences across all 25+ locations.",
    keyFeatures: [
      { icon: "Check", title: "Smart scheduling", desc: "AI-powered booking matching technician skills, bay availability, and estimated service time." },
      { icon: "Wrench", title: "Parts ordering", desc: "Automated sourcing with distributor API integration, price comparison, and PO generation." },
      { icon: "People", title: "Unified customer profiles", desc: "Cross-location database with full service history, vehicle details, and communication log." },
      { icon: "Car", title: "Vehicle management", desc: "Complete records with VIN lookup, maintenance schedules, recall alerts, and recommendations." },
      { icon: "Alert", title: "Automated reminders", desc: "SMS and email reminders for upcoming services, confirmations, and satisfaction surveys." },
      { icon: "Chart", title: "Performance analytics", desc: "Location-level dashboards for revenue, bay utilisation, and technician productivity." },
      { icon: "File", title: "Invoicing & payments", desc: "Automated invoice generation with service itemisation, parts markup, and integrated payments." },
      { icon: "Smartphone", title: "Customer app", desc: "Self-service booking, real-time service tracking, digital invoices, and maintenance history." },
    ],
    results: [{ value: "25+", label: "Service centres" }, { value: "70%", label: "Faster booking" }, { value: "95%", label: "Parts accuracy" }, { value: "30%", label: "Retention increase" }],
    techStack: ["React", "Node.js", "PostgreSQL", "Redis", "Twilio", "REST APIs", "Docker", "AWS"],
  },
  {
    slug: "ai-motherhood-app",
    title: "AI-Driven Motherhood App",
    client: "A digital health startup",
    industry: "Healthcare & AI",
    categories: ["Healthcare", "AI & ML"],
    subtitle: "ML-powered maternal health companion with personalised care plans, symptom tracking, and wearable integration.",
    overview: "An AI-driven motherhood app supporting mothers from pregnancy through early childhood with ML-powered personalised care plans, wearable integration, intelligent symptom triage, and 24/7 AI chatbot guidance.",
    challenge: "A digital health startup wanted a comprehensive maternal health companion supporting mothers from pregnancy through the first two years of childhood. Existing apps offered generic content, no personalisation, no wearable integration, and no mechanism for connecting users with certified providers for urgent concerns.",
    solution: "We developed an AI-driven app featuring ML-powered personalised care plans that adapt based on health data, pregnancy stage, risk factors, and lifestyle inputs. It includes symptom tracking with intelligent triage, wearable integration for continuous vitals monitoring, an AI chatbot trained on maternal health guidelines, a curated content engine, provider booking, and an expert-moderated community forum.",
    keyFeatures: [
      { icon: "Cpu", title: "ML care plans", desc: "Personalised plans adapting to pregnancy stage, health data, risk factors, and lifestyle inputs." },
      { icon: "Heart", title: "Smart symptom triage", desc: "Intelligent logging with pattern recognition flagging concerning combinations for provider review." },
      { icon: "Watch", title: "Wearable integration", desc: "HealthKit and Google Fit integration for continuous heart rate, sleep, and activity." },
      { icon: "Bot", title: "AI health chatbot", desc: "24/7 AI chatbot trained on maternal health guidelines for guidance and FAQ responses." },
      { icon: "File", title: "Content engine", desc: "Curated articles, videos, and tips delivered based on pregnancy stage and preferences." },
      { icon: "Check", title: "Provider booking", desc: "In-app OB-GYN appointment scheduling with telehealth video consultation support." },
      { icon: "People", title: "Community forum", desc: "Expert-moderated community with topic groups, Q&A threads, and peer support networks." },
      { icon: "Chart", title: "Progress tracking", desc: "Visual pregnancy milestones, weight tracking, kick counter, and contraction timer tools." },
    ],
    results: [{ value: "150K+", label: "Active users" }, { value: "92%", label: "Satisfaction score" }, { value: "45%", label: "Fewer unnecessary ER visits" }, { value: "4.8", label: "App store rating" }],
    techStack: ["React Native", "Python", "TensorFlow", "Node.js", "MongoDB", "Firebase", "AWS", "HealthKit"],
  },
  {
    slug: "cleaning-marketplace",
    title: "On-Demand Cleaning Marketplace",
    client: "A home services company",
    industry: "Marketplace",
    categories: ["Marketplace"],
    subtitle: "Marketplace connecting homeowners with 5K+ vetted cleaning professionals with instant booking and real-time tracking.",
    overview: "An on-demand cleaning marketplace with instant booking, intelligent provider matching, real-time job tracking, and a satisfaction guarantee system.",
    challenge: "A home services company offering professional cleaning across major cities was managing bookings through phone calls and email, with manual assignment of cleaning professionals. Customer wait times averaged 4 hours, provider no-shows were 12%, and there was no standardised quality assurance — leading to a 3.2-star average review.",
    solution: "We built an on-demand marketplace with instant booking, real-time provider matching on location, availability, ratings, and specialisation. Features include automated scheduling, provider background checks, in-app messaging, real-time job tracking, a dynamic pricing engine, and a satisfaction guarantee workflow with automated rebooking.",
    keyFeatures: [
      { icon: "Bolt", title: "Instant booking", desc: "Sub-30-second booking with real-time availability, dynamic pricing, and instant confirmation." },
      { icon: "Check", title: "Smart matching", desc: "Algorithm matching customers with providers based on location, ratings, specialisation, and availability." },
      { icon: "Pin", title: "Real-time tracking", desc: "Live provider location and job status with ETA updates and arrival notifications." },
      { icon: "Money", title: "Dynamic pricing", desc: "Pricing engine factoring property size, service type, frequency, and demand surge." },
      { icon: "Shield", title: "Background checks", desc: "Integrated identity verification and background screening with ongoing compliance monitoring." },
      { icon: "Chat", title: "In-app messaging", desc: "Real-time chat between customers and providers with photo sharing and job detail clarification." },
      { icon: "Refresh", title: "Satisfaction guarantee", desc: "Automated rebooking workflow for unsatisfied customers with quality follow-up and coaching." },
      { icon: "Star", title: "Review system", desc: "Two-way rating with fraud detection, sentiment analysis, and provider quality scoring." },
    ],
    results: [{ value: "5K+", label: "Service providers" }, { value: "< 30s", label: "Average booking time" }, { value: "4.8", label: "Customer rating" }, { value: "3%", label: "No-show rate" }],
    techStack: ["React", "Node.js", "PostgreSQL", "Stripe", "Google Maps API", "Redis", "AWS", "Socket.io"],
  },
  {
    slug: "loyalty-app",
    title: "Multi-tier Loyalty App for Manufacturers & Dealers",
    client: "A consumer goods manufacturer",
    industry: "Enterprise",
    categories: ["Enterprise & CRM"],
    subtitle: "Four-tier loyalty ecosystem spanning manufacturers, dealers, agents, and end customers.",
    overview: "A four-tier loyalty app connecting manufacturers, dealers, agents, and end customers in a single ecosystem with QR-based scanning, gamification, tier-based rewards, and AI-powered demand forecasting.",
    challenge: "A consumer goods manufacturer selling through a multi-tier distribution network had zero visibility into downstream sales and no mechanism to incentivise channel partners. Dealer engagement was declining, agents lacked motivation, and the manufacturer could not track end-customer behaviour — causing inaccurate demand forecasting and excess inventory.",
    solution: "We built a four-tier loyalty app connecting all stakeholders. Manufacturers configure reward programmes; dealers earn tier-based incentives on purchase volumes; agents accumulate points with leaderboards and gamification; end customers scan QR codes on products to earn points. Real-time analytics, geo-tagged activity maps, and AI demand forecasting complete the picture.",
    keyFeatures: [
      { icon: "Layers", title: "Four-tier architecture", desc: "Separate experiences for manufacturers, dealers, agents, and customers with role-based rewards." },
      { icon: "Qr", title: "QR product scanning", desc: "End customers scan product QR codes to earn points, giving manufacturers downstream visibility." },
      { icon: "Trophy", title: "Gamification & leaderboards", desc: "Agent leaderboards, badges, streak rewards, and tier-based competitions to drive engagement." },
      { icon: "Gift", title: "Reward marketplace", desc: "Configurable reward catalogue with points redemption, cashback, and promotional offers." },
      { icon: "Alert", title: "Campaign builder", desc: "Manufacturer tools for targeted promotions, bonus-point events, and seasonal incentives." },
      { icon: "Map", title: "Geo-tagged analytics", desc: "Activity maps showing sales patterns, partner density, and engagement hotspots by region." },
      { icon: "Cpu", title: "Demand forecasting", desc: "AI-powered predictions based on loyalty engagement data to improve inventory planning." },
      { icon: "Chart", title: "Tier-wise reporting", desc: "Granular analytics per tier with conversion funnels, engagement metrics, and ROI tracking." },
    ],
    results: [{ value: "4", label: "Stakeholder tiers" }, { value: "10K+", label: "Channel partners" }, { value: "35%", label: "Dealer engagement lift" }, { value: "25%", label: "Forecast accuracy lift" }],
    techStack: ["React Native", "Node.js", "PostgreSQL", "Redis", "Firebase", "REST APIs", "AWS", "QR SDK"],
  },
  {
    slug: "pharma-crm",
    title: "MMS CRM for Pharma",
    client: "A pharmaceutical company",
    industry: "Healthcare & Pharma",
    categories: ["Healthcare", "Enterprise & CRM"],
    subtitle: "Field rep management with sample tracking, doctor visit scheduling, and compliance reporting.",
    overview: "An MMS CRM for pharmaceutical field operations with GPS-verified doctor visits, sample tracking with audit trails, intelligent route planning, and executive territory analytics.",
    challenge: "A pharmaceutical company with 200+ field medical representatives was tracking visits, sample distributions, and expenses through Excel and email. Sample inventory was frequently inaccurate leading to compliance violations, and management had no real-time visibility into field activity.",
    solution: "We developed an MMS CRM with GPS-verified doctor visits, sample inventory management from warehouse to doctor with audit trails, intelligent route planning, expense management with OCR, and executive dashboards showing territory heatmaps, rep scorecards, and prescription influence analytics.",
    keyFeatures: [
      { icon: "Pin", title: "GPS visit verification", desc: "Geo-tagged visit logging with automatic timestamps and location proof for compliance." },
      { icon: "Pill", title: "Sample tracking", desc: "End-to-end inventory from warehouse to doctor with barcode scanning and audit trails." },
      { icon: "Map", title: "Smart route planning", desc: "AI-optimised daily routes based on doctor priority, location, frequency, and traffic." },
      { icon: "File", title: "Auto call reports", desc: "Pre-populated reports with doctor history, discussion notes, and follow-up actions." },
      { icon: "File", title: "Expense management", desc: "Receipt OCR, auto-categorisation, approval workflows, and reimbursement tracking." },
      { icon: "Map", title: "Territory heatmaps", desc: "Visual analytics showing coverage density, visit frequency, and opportunity gaps." },
      { icon: "Trophy", title: "Rep scorecards", desc: "Call rates, coverage targets, sample utilisation, and engagement quality scores." },
      { icon: "Chart", title: "Prescription analytics", desc: "Influence tracking correlating field activity with doctor prescribing patterns." },
    ],
    results: [{ value: "200+", label: "Field reps" }, { value: "40%", label: "More doctor visits" }, { value: "99.5%", label: "Sample compliance" }, { value: "50%", label: "Reporting time saved" }],
    techStack: ["React", "Node.js", "PostgreSQL", "Google Maps API", "Redis", "Docker", "AWS"],
  },
  {
    slug: "patient-ehr",
    title: "Patient EHR Portal",
    client: "A multi-specialty clinic network",
    industry: "Healthcare",
    categories: ["Healthcare"],
    subtitle: "HIPAA-compliant electronic health records portal with HL7 FHIR integration across 30+ clinics.",
    overview: "A HIPAA-compliant Patient EHR Portal with HL7 FHIR integration connecting 30+ multi-specialty clinics with unified patient timelines, clinical decision support, and a patient-facing portal.",
    challenge: "A network of 30+ multi-specialty clinics was storing patient records across disconnected legacy systems — some paper, others desktop. Patients had to repeat history at each visit, lab results took days to reach referring physicians, and lack of a unified system caused medication interaction risks and billing errors. Average check-in was 20 minutes.",
    solution: "We built a HIPAA-compliant EHR Portal with HL7 FHIR integration across all 30+ clinics. It includes a unified patient timeline, a patient-facing portal for appointments, refills, messaging, and results, role-based access, clinical decision support alerts for drug interactions and allergies, and integrated billing with ICD-10 suggestions.",
    keyFeatures: [
      { icon: "Clock", title: "Unified patient timeline", desc: "Chronological view of all interactions, results, and notes across clinics and specialties." },
      { icon: "Shield", title: "HIPAA compliance", desc: "End-to-end encryption, audit logging, role-based access, and automated compliance reporting." },
      { icon: "Plug", title: "HL7 FHIR integration", desc: "Standards-based data exchange enabling interoperability with labs, pharmacies, and other systems." },
      { icon: "Alert", title: "Clinical decision support", desc: "Automated alerts for drug interactions, allergy warnings, and contraindication checks at point of care." },
      { icon: "People", title: "Role-based access", desc: "Granular permissions for physicians, nurses, lab techs, billing staff, and administrators." },
      { icon: "File", title: "e-Prescribing", desc: "Electronic prescriptions with pharmacy routing, refill management, and controlled substance tracking." },
      { icon: "Money", title: "Integrated billing", desc: "Automated coding with ICD-10 suggestions, claim generation, and payment reconciliation." },
      { icon: "Smartphone", title: "Patient portal", desc: "Self-service booking, secure messaging, lab results, and refill requests." },
    ],
    results: [{ value: "30+", label: "Clinics connected" }, { value: "80%", label: "Faster check-in" }, { value: "99.9%", label: "HIPAA compliance score" }, { value: "45%", label: "Billing errors reduction" }],
    techStack: ["React", "Node.js", "PostgreSQL", "HL7 FHIR", "AWS", "Docker", "Redis"],
  },
  {
    slug: "patient-iot-monitoring",
    title: "Patient Care Portal with IoT Bed & Sensors",
    client: "A regional hospital group",
    industry: "Healthcare & IoT",
    categories: ["Healthcare", "IoT & Telematics"],
    subtitle: "Smart hospital beds and wearable sensors streaming real-time vitals to care dashboards.",
    overview: "A Patient Care Portal integrating IoT-enabled smart beds, wearable sensors, and environmental monitors streaming real-time vitals to care dashboards.",
    challenge: "A regional hospital group with 500+ beds across 3 facilities relied on manual vital checks every 2–4 hours. Deterioration detection-to-response averaged 45 minutes outside the ICU, fall incidents in elderly wards averaged 8 per month, and general wards had no continuous monitoring infrastructure.",
    solution: "We developed a Patient Care Portal integrating IoT smart beds with pressure sensors for fall detection, wearable sensors streaming continuous vitals, and environmental sensors — all via MQTT to a real-time care dashboard with configurable thresholds per acuity level. Features include auto-calculated early warning scores, escalation workflows, historical trend analysis, and a family portal.",
    keyFeatures: [
      { icon: "Bed", title: "Smart bed sensors", desc: "Pressure sensors for fall detection, position monitoring, and bed-exit alerts for at-risk patients." },
      { icon: "Heart", title: "Continuous vitals", desc: "Wearables streaming heart rate, SpO2, respiration, and temperature every 30 seconds." },
      { icon: "Gauge", title: "Early warning scores", desc: "Auto-calculated EWS from streaming vitals with configurable thresholds per acuity level." },
      { icon: "Alert", title: "Alert escalation", desc: "Multi-tier nurse alerts via mobile and pager with acknowledgement and auto-escalation." },
      { icon: "Cloud", title: "Environmental monitoring", desc: "Bedside sensors tracking room temperature, humidity, and noise for patient comfort." },
      { icon: "Chart", title: "Trend analysis", desc: "Historical vitals with ML deterioration prediction and discharge-readiness assessment." },
      { icon: "People", title: "Family portal", desc: "Secure family access to approved vitals, care updates, and visit scheduling." },
      { icon: "Plug", title: "System integration", desc: "HL7/FHIR integration with existing hospital information and nurse call systems." },
    ],
    results: [{ value: "500+", label: "Smart beds" }, { value: "70%", label: "Faster detection" }, { value: "60%", label: "Fewer falls" }, { value: "15 min", label: "Avg response time" }],
    techStack: ["Python", "IoT sensors", "MQTT", "React", "Node.js", "InfluxDB", "Grafana", "AWS IoT"],
  },
  {
    slug: "cashless-shopping",
    title: "Cashless Shopping Marketplace App",
    client: "A retail innovation startup",
    industry: "FinTech & Retail",
    categories: ["Marketplace", "eCommerce & Retail"],
    subtitle: "QR-based cashless payments with multi-merchant marketplace and real-time settlement.",
    overview: "A cashless shopping marketplace app with QR-based payments requiring zero hardware from merchants, a multi-merchant digital wallet, integrated loyalty, and real-time settlement.",
    challenge: "A retail innovation startup wanted a frictionless cashless experience for a network of local merchants. Existing solutions charged 3–4% per transaction, offered no loyalty integration, no customer analytics, and required expensive POS upgrades.",
    solution: "We built a cashless marketplace app with QR-based payments requiring zero hardware investment, a multi-merchant digital wallet with instant settlement, an integrated cross-merchant loyalty points system, a merchant dashboard with customer analytics, a customer app with nearby merchant discovery and order-ahead, and a real-time settlement engine processing funds within minutes.",
    keyFeatures: [
      { icon: "Qr", title: "QR payments", desc: "Scan-to-pay with zero POS hardware requirements — merchants just display a QR code." },
      { icon: "Wallet", title: "Digital wallet", desc: "Multi-merchant wallet with balance management, auto-top-up, and transaction history." },
      { icon: "Coin", title: "Cross-merchant loyalty", desc: "Earn and redeem loyalty points across all participating merchants in the network." },
      { icon: "Bolt", title: "Instant settlement", desc: "Real-time settlement engine delivering funds to merchants within minutes, not days." },
      { icon: "Pin", title: "Merchant discovery", desc: "Location-based nearby merchant finder with categories, ratings, and current offers." },
      { icon: "Cart", title: "Order ahead", desc: "Pre-order and pre-pay at participating merchants for skip-the-line pickup." },
      { icon: "Chart", title: "Merchant analytics", desc: "Customer demographics, purchasing patterns, peak hours, and loyalty ROI." },
      { icon: "Shield", title: "Fraud detection", desc: "ML-powered transaction monitoring with velocity checks, anomaly detection, and dispute management." },
    ],
    results: [{ value: "500+", label: "Merchants onboarded" }, { value: "1.2%", label: "Transaction fee" }, { value: "85K+", label: "Active shoppers" }, { value: "< 5 min", label: "Settlement time" }],
    techStack: ["React Native", "Node.js", "PostgreSQL", "Redis", "Stripe Connect", "Firebase", "AWS"],
  },
  {
    slug: "food-ordering",
    title: "Food Ordering Marketplace",
    client: "A restaurant technology company",
    industry: "Marketplace",
    categories: ["Marketplace"],
    subtitle: "Multi-restaurant ordering platform with real-time delivery tracking and driver management.",
    overview: "A full-stack food ordering marketplace connecting 200+ restaurants with customers and delivery drivers — featuring real-time order tracking, intelligent driver assignment, POS integration, and city-level operational dashboards.",
    challenge: "A restaurant technology company wanted to launch a multi-restaurant food ordering marketplace serving a metro area with 200+ restaurants. They needed to compete with established platforms by offering lower commission rates while providing a superior experience for all three sides of the marketplace.",
    solution: "We developed a full-stack marketplace with a customer app featuring discovery, real-time menu updates, group ordering, and scheduled delivery. The restaurant portal includes POS-integrated order management, menu builder with modifier chains, and analytics. The delivery system features intelligent driver assignment, real-time GPS tracking, and an admin panel with commission management, dispute resolution, and city-level dashboards.",
    keyFeatures: [
      { icon: "Search", title: "Restaurant discovery", desc: "Cuisine filters, ratings, delivery ETAs, and personalised recommendations from order history." },
      { icon: "Plug", title: "POS integration", desc: "Real-time order sync with major restaurant POS systems for seamless kitchen workflow." },
      { icon: "Bowl", title: "Menu builder", desc: "Visual menu editor with modifier chains, combo deals, availability scheduling, and photos." },
      { icon: "Car", title: "Smart dispatch", desc: "AI driver assignment considering proximity, current load, route efficiency, and traffic." },
      { icon: "Pin", title: "Live tracking", desc: "Real-time GPS tracking with accurate ETAs and status updates for customers." },
      { icon: "People", title: "Group ordering", desc: "Shared cart for office and group orders with payment splitting and customisation." },
      { icon: "Tag", title: "Promotions engine", desc: "Tools for restaurant promotions, platform deals, referrals, and surge pricing." },
      { icon: "Chart", title: "City operations", desc: "Operational dashboards with order heatmaps, driver coverage, and revenue analytics." },
    ],
    results: [{ value: "200+", label: "Restaurant partners" }, { value: "50K+", label: "Monthly orders" }, { value: "28 min", label: "Avg delivery time" }, { value: "4.7", label: "Avg app rating" }],
    techStack: ["React Native", "Node.js", "PostgreSQL", "Redis", "Google Maps API", "Socket.io", "Stripe"],
  },
  {
    slug: "physed-health",
    title: "Physical Education & Health Platform",
    client: "An education technology company",
    industry: "Education & Health",
    categories: ["Healthcare", "Education & Fitness"],
    subtitle: "Digital PE curriculum platform with fitness assessments, progress tracking, and educator tools.",
    overview: "A comprehensive Physical Education and Health platform with standards-aligned curriculum delivery, digital fitness assessments, longitudinal student progress tracking, parent portals, and district-wide compliance reporting.",
    challenge: "Physical education teachers across school districts were still using paper-based fitness assessments, had no standardised curriculum delivery tools, and lacked any mechanism to track student fitness progress over multiple academic years. State PE standards compliance was difficult to verify, and parents had no visibility into their children's PE activities.",
    solution: "We built a PE and Health platform enabling teachers to deliver standards-aligned curriculum with lesson plans, activity libraries, and adaptive modifications. The assessment module digitises tests like PACER, curl-ups, and sit-and-reach with auto-scoring against national benchmarks. Student dashboards track fitness metrics longitudinally, a parent portal provides activity summaries, and admin tools enable district-wide compliance reporting.",
    keyFeatures: [
      { icon: "Book", title: "Standards-aligned curriculum", desc: "Pre-built lesson plans aligned to state PE standards with activity libraries and modifications." },
      { icon: "Clock", title: "Digital fitness testing", desc: "Digitised PACER, curl-ups, sit-and-reach, and other tests with auto-scoring and benchmarking." },
      { icon: "Chart", title: "Progress tracking", desc: "Longitudinal fitness metrics across academic years with trend visualisation and growth analysis." },
      { icon: "Check", title: "Adaptive modifications", desc: "Activity modifications for students with disabilities, injuries, or different ability levels." },
      { icon: "People", title: "Class management", desc: "Student roster management, attendance tracking, grading tools, and behaviour logging." },
      { icon: "Building", title: "Parent portal", desc: "Activity summaries, fitness reports, and achievement notifications for parents and guardians." },
      { icon: "Shield", title: "District compliance", desc: "Automated state standards compliance reporting with coverage analytics and audit trails." },
      { icon: "File", title: "Report generation", desc: "Automated PDF reports for student fitness cards, class summaries, and district analytics." },
    ],
    results: [{ value: "500+", label: "Schools" }, { value: "200K+", label: "Students assessed" }, { value: "75%", label: "Time saved on assessments" }, { value: "100%", label: "Standards compliance" }],
    techStack: ["React", "Node.js", "PostgreSQL", "AWS", "Docker", "Redis"],
  },
];

// -------------------- BLOG ARTICLES -------------------- //
export type Article = {
  slug: string;
  title: string;
  subtitle: string;
  date: string;
  readTime: string;
  sections: { heading: string; body: string }[];
};

export const ARTICLES: Article[] = [
  {
    slug: "enterprise-ai-adoption-2026",
    title: "The Enterprise AI Adoption Playbook for 2026",
    subtitle: "A practical guide to implementing AI across your organisation.",
    date: "March 15, 2026",
    readTime: "8 min read",
    sections: [
      { heading: "The AI adoption imperative", body: "In 2026, enterprises that have not begun their AI journey face an existential competitive threat. According to recent industry surveys, 78% of Fortune 500 companies have at least one AI system in production, up from just 35% three years ago. The gap between AI adopters and laggards is widening at an accelerating pace." },
      { heading: "Step 1: Assess your AI readiness", body: "Before investing in AI, organisations must honestly evaluate their data infrastructure, team capabilities, and organisational culture. The three pillars of AI readiness are: data quality and accessibility, technical talent and skills, and executive sponsorship with clear business objectives." },
      { heading: "Step 2: Identify high-impact use cases", body: "Start with use cases that combine high business value with technical feasibility. Common early wins include customer service automation, demand forecasting, fraud detection, and document processing. Avoid the trap of pursuing moonshot projects before building foundational capabilities." },
      { heading: "Step 3: Build vs buy vs partner", body: "For most enterprises, the optimal approach is a hybrid: buy commodity AI capabilities (OCR, basic NLP), partner with specialists for domain-specific solutions, and build custom models only for true competitive differentiators. This balances speed-to-market with long-term strategic advantage." },
      { heading: "Step 4: Establish AI governance", body: "Responsible AI deployment requires governance frameworks covering model bias testing, data privacy compliance, explainability requirements, and ongoing monitoring. Organisations that establish governance early avoid costly remediation and reputational risks later." },
    ],
  },
  {
    slug: "rag-vs-traditional-search",
    title: "Why RAG is Replacing Traditional Search",
    subtitle: "How retrieval-augmented generation is transforming enterprise knowledge.",
    date: "March 8, 2026",
    readTime: "6 min read",
    sections: [
      { heading: "The limits of traditional search", body: "Keyword-based search has served enterprises well for decades, but it fundamentally breaks down when users need answers rather than links. Traditional search returns documents; RAG returns precise, source-cited answers synthesised from your entire knowledge base." },
      { heading: "How RAG works", body: "Retrieval-Augmented Generation combines two powerful capabilities: semantic retrieval that finds relevant information across thousands of documents, and generative AI that synthesises those sources into coherent, contextual answers. The result is an AI assistant that knows everything your organisation knows." },
      { heading: "RAG vs fine-tuning", body: "While fine-tuning bakes knowledge into model weights (expensive and quickly outdated), RAG retrieves knowledge at query time from your live document store. This means RAG stays current automatically, costs less to maintain, and provides source citations for every claim." },
      { heading: "Implementation best practices", body: "Successful RAG implementations require careful attention to chunking strategy, embedding model selection, hybrid search combining dense and sparse retrieval, and thoughtful prompt engineering. The quality of retrieval directly determines the quality of generated answers." },
    ],
  },
  {
    slug: "scalable-microservices-node",
    title: "Building Scalable Microservices with Node.js",
    subtitle: "Architecture patterns for high-throughput distributed systems.",
    date: "February 28, 2026",
    readTime: "7 min read",
    sections: [
      { heading: "Why microservices at scale", body: "Monolithic architectures become a liability as applications grow. Microservices enable independent deployment, technology diversity, fault isolation, and team autonomy. Node.js, with its event-driven architecture and massive ecosystem, is ideally suited for high-throughput microservices." },
      { heading: "Designing service boundaries", body: "The most critical decision in microservices architecture is defining service boundaries. Domain-Driven Design provides the best framework: identify bounded contexts through event storming, then map each context to a service with its own data store and API contract." },
      { heading: "Inter-service communication", body: "Synchronous REST or gRPC for queries and asynchronous event-driven messaging for commands. Use Apache Kafka or RabbitMQ for event streaming, implement circuit breakers, and design for eventual consistency rather than distributed transactions." },
      { heading: "Observability & resilience", body: "In distributed systems, observability is not optional. Implement structured logging, distributed tracing with OpenTelemetry, and metrics collection with Prometheus. Combine with health checks, retry policies, and graceful degradation for production-grade resilience." },
    ],
  },
  {
    slug: "ai-native-mobile-apps",
    title: "The Future of Mobile: AI-Native Apps",
    subtitle: "How on-device AI is reshaping the mobile development landscape.",
    date: "February 20, 2026",
    readTime: "5 min read",
    sections: [
      { heading: "The on-device AI revolution", body: "With Apple Intelligence, Google Gemini Nano, and Qualcomm AI Engine, mobile devices now run sophisticated AI models locally. This shift enables real-time processing without network latency, offline functionality, and enhanced privacy since data never leaves the device." },
      { heading: "Core ML vs TensorFlow Lite", body: "iOS developers leverage Core ML for seamless model integration with Swift, while Android developers use TensorFlow Lite or ONNX Runtime. Both platforms now support hardware-accelerated inference on neural processing units (NPUs) for near-instant predictions." },
      { heading: "Practical on-device AI use cases", body: "Real-time camera effects, voice command processing, predictive text with personal context, document scanning with instant OCR, health monitoring from sensor data, and offline translation are all now achievable entirely on-device with sub-50ms latency." },
      { heading: "Designing AI-native experiences", body: "AI-native apps do not just add AI features to existing UX — they fundamentally rethink the interaction model. Think proactive suggestions instead of search, natural language interfaces instead of forms, and adaptive UIs that learn from user behaviour." },
    ],
  },
  {
    slug: "cloud-cost-optimization",
    title: "Cloud Cost Optimisation: A Technical Guide",
    subtitle: "Strategies to cut your cloud bill by 40% without sacrificing performance.",
    date: "February 12, 2026",
    readTime: "6 min read",
    sections: [
      { heading: "The cloud cost crisis", body: "Cloud spending grew 29% year-over-year, with the average enterprise wasting 32% of their cloud budget on idle or over-provisioned resources. Without deliberate optimisation, cloud costs compound rapidly and often exceed the savings from migrating off on-premise infrastructure." },
      { heading: "Right-sizing and reserved capacity", body: "Start with right-sizing: analyse actual CPU, memory, and network utilisation over 30 days. Most instances run under 40% utilisation. Combine right-sizing with Reserved Instances or Savings Plans for predictable workloads to achieve 30–60% cost reductions." },
      { heading: "Spot instances and serverless", body: "For fault-tolerant workloads (batch processing, CI/CD, data pipelines), spot instances offer 60–90% discounts. For event-driven workloads, serverless functions eliminate idle costs entirely. The key is matching the pricing model to the workload pattern." },
      { heading: "FinOps as a practice", body: "Sustainable cost optimisation requires cultural change, not just technical fixes. Implement tagging standards, create team-level cost dashboards, set budget alerts, and conduct monthly cost reviews. FinOps makes cloud cost a shared responsibility across engineering and finance." },
    ],
  },
  {
    slug: "computer-vision-manufacturing-qa",
    title: "Computer Vision in Manufacturing QA",
    subtitle: "Automated visual inspection systems that outperform human reviewers.",
    date: "February 5, 2026",
    readTime: "7 min read",
    sections: [
      { heading: "The quality control challenge", body: "Manufacturing quality inspection has traditionally relied on human visual inspection — a process that is slow, inconsistent, and prone to fatigue-related errors. With defect rates as low as 0.1%, inspectors must maintain concentration while examining thousands of identical parts per shift." },
      { heading: "How computer vision changes the game", body: "Modern computer vision systems use convolutional neural networks trained on thousands of defect images to detect anomalies at superhuman speed and consistency. These systems inspect every single unit — not just samples — and can detect sub-millimeter defects invisible to the human eye." },
      { heading: "Implementation architecture", body: "A typical deployment includes high-resolution industrial cameras, edge compute units running optimised inference models (TensorRT/ONNX), real-time reject mechanisms, and a cloud backend for model retraining and analytics. The edge-cloud hybrid ensures low latency for production line speeds." },
      { heading: "Measuring ROI", body: "Our manufacturing clients typically see 99.2%+ defect detection rates (vs 85% human baseline), 3× inspection throughput, 60% reduction in quality-related returns, and payback within 8–12 months. The data generated also feeds continuous improvement of manufacturing processes." },
    ],
  },
];
